apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "chart.name" . }}-shared-pvc
  labels:
    labels:
      app: {{ template "chart.name" . }}
      chart: {{ template "chart.labels" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedVolume.storage.size }}
  storageClassName: "{{ .Values.sharedVolume.className }}"