apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}