name: 'Brakeman Audit'
run-name: Brakeman Audit of ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  brakeman-audit:
    uses: scientist-softserv/actions/.github/workflows/brakeman-audit.yaml@add-brakeman-action
    with:
      webTarget: web
      tag: latest