name: "Bundler Audit"
run-name: Bundler Audit (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }}
on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run bundler-audit
      run: |
        gem install bundler-audit
        bundle exec bundle-audit check --update

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: bundler-audit-report
        path: report*.txt
